# Generated by Django 3.0.8 on 2020-07-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_Name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_Num',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='year',
            new_name='sem_year',
        ),
        migrations.RenameField(
            model_name='prerequisite',
            old_name='pre_req1',
            new_name='prereq1',
        ),
        migrations.RenameField(
            model_name='prerequisite',
            old_name='pre_req2',
            new_name='prereq2',
        ),
    ]
